@isTest
public class CreateTestDataTest {
/*   static testMethod void testData*Creation()
    {
        CreateTestData ctd = new CreateTestData();
        Account paccount = ctd.createPersonalAccount();
        insert paccount;
        User u = ctd.createCustomerCommunityUser(paccount);
        //insert u;
        
        Account acc = ctd.createAccount();
        //insert acc;
        Contact con = ctd.createContact(paccount);
        //insert con;
        
        Lead ld = ctd.createLead(acc);
        //insert ld;
        
        Account dealer = ctd.createDealer();
        //insert dealer;
        
        Account dealer_jp = ctd.createDealer('jp');
        //insert dealer_jp;
    }
    static testMethod void testProducts()
    {
        Test.startTest();
        CreateTestData ctd = new CreateTestData();   
        Vehicle_Specification__c spec = ctd.createVehicleSpecofocation();
        insert spec;
        
        Product2 prod = ctd.createProduct(spec);
        insert prod;
        
        Vehicle_Specification__c maker = ctd.createMaker();
        Asset ast = ctd.createAsset();
        //insert ast;
        Asset jp_ast = ctd.createAsset('jp');
        //insert jp_ast;
        
       // Product2 prod = ctd.createProduct();
        List<Product2> prods = ctd.createProducts();
        List<Asset> asts = ctd.createAssets();
        //insert asts;
        List<Asset> jp_asts  = ctd.createAssets('jp');
        test.stopTest();
        
    }
    
    static testMethod void testSavedVehicles()
    {
        CreateTestData ctd = new CreateTestData();
        Vehicle_Specification__c maker = ctd.createMaker();
        List<Saved_Vehicle_for_Lead__c> leads = ctd.createSavedVehicleForLead();
        List<Saved_Vehicle_for_Account__c> accs = ctd.createSavedVehicle();
        
        Opportunity opp = ctd.createOpportunity(Date.today(), 'Save a Quote');
        JUDAAN_Date__c jdate = ctd.createExpireDay(3, 7, 7);
        
        ctd.createColourMapping();
        
        JUDAAN_Campaign__c cmp = ctd.createCampaigndata();
        ctd.createCampaign();
        
        ctd.loadJUDAANMarketSettingsData();
        ctd.loadTradeinSetting();
    }
    
    static testMethod void testOpps()
    {
        CreateTestData ctd = new CreateTestData();
        List<Opportunity> opps = ctd.createOpportunities(Date.today(), 'Save a Quote');
    } */
}