public class FinanceUpload_Constants {
    public static final String PROCESS_NAME = 'Finance';
    public static final String SYSTEM_USER='00524000001fd7g';

    public static final String EMAIL_COLUMN_HEADER = 'Email';
    public static final String PHONE_COLUMN_HEADER = 'Phone';
    public static final String VIN_COLUMN_HEADER = 'VIN';
    public static final String REGISTRATION_COLUMN_HEADER = 'Registration Number';
    public static final String FINANCE_REFERENCE_COLUMN_HEADER = 'Finance Reference';
    public static final String BRAND_COLUMN_HEADER = 'Brand';
    public static final String CORPORATE_COLUMN_HEADER = 'CorporateAccIndicator';
    public static final String DEALER_CODE_COLUMN_HEADER = 'Dealer Code JLR';
    public static final String LAST_NAME_COLUMN_HEADER = 'Last Name';
    public static final String FIRST_NAME_COLUMN_HEADER = 'First Name';
    public static final String LEGAL_ENTITY_ID='Customer ID';
    public static final String MOBILE_NUMBER='Mobile Number';
    
}