@isTest
public class FinanceUpload_Constants_T {
    static testMethod void testStrings()
    {
        


        System.Assertequals(FinanceUpload_Constants.PROCESS_NAME,'Finance');
        System.Assertequals(FinanceUpload_Constants.PHONE_COLUMN_HEADER ,'Phone');
        System.Assertequals(FinanceUpload_Constants.REGISTRATION_COLUMN_HEADER ,'Registration Number');
        System.Assertequals(FinanceUpload_Constants.BRAND_COLUMN_HEADER ,'Brand');
        System.Assertequals(FinanceUpload_Constants.CORPORATE_COLUMN_HEADER ,'CorporateAccIndicator');
        System.Assertequals(FinanceUpload_Constants.DEALER_CODE_COLUMN_HEADER ,'Dealer Code JLR');
        System.Assertequals(FinanceUpload_Constants.LAST_NAME_COLUMN_HEADER ,'Last Name');
        System.Assertequals(FinanceUpload_Constants.FIRST_NAME_COLUMN_HEADER ,'First Name');
 
    }

   
}