@isTest
public class FirstOpportunityProduct_Test {

    public static testmethod void Controller_ReturnsAllProductIds_GivenOpportunityThatHasProducts(){
        /* Todo - This method causing problems. Commenting out to facilitate a deployment - Grant Millgate
        OpportunityLineItem oli = TestClass_OppLineItemCreator.CreateOppLineItem();
        insert oli;
        List<OpportunityLineItem> testResult = FirstOpportunityProduct_LC_Controller.getOpportunityProducts(oli.OpportunityId);
        System.assertEquals(1, testResult.size());
        *
        */
    }


}