public class RoadsideUpload_Constants {
	public static final String EMAIL_COLUMN_HEADER = 'Email';
	public static final String PHONE_COLUMN_HEADER = 'Phone';
	public static final String VIN_COLUMN_HEADER = 'VIN';
	public static final String REGISTRATION_COLUMN_HEADER = 'Registration';
	public static final String MILEAGE_COLUMN_HEADER = 'Current Vehicle Mileage';
	public static final String MILEAGE_UOM_COLUMN_HEADER = 'Miles UOM';	
}