public class VehicleSpecificationByNameRetriever {    
    /*public Vehicle_Specification__c RetrieveDerivative(string make, string model, string derivativeName)
    {
    	List<Vehicle_Specification__c> derivatives = [Select Model__c, Make__c From Vehicle_Specification__c 
    		Where Name=:derivativeName And Model__r.Name=:model And Make__r.Name=:make Limit 1];
    		
    	if(derivatives.size() < 1){ return new Vehicle_Specification__c(); }
		return derivatives[0];
    }*/
}